version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: paymentdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
#  app:
#    build: .
#    ports:
#      - "3000:3000"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/paymentdb
#      - SPRING_DATASOURCE_USERNAME=user
#      - SPRING_DATASOURCE_PASSWORD=password
#    depends_on:
#      - mysql
volumes:
  mysql-data: